# <font color="#49699E" size=40>Supervised Learning with Regression and Cross-Validation</font>

# LEARNING OBJECTIVES
# LEARNING MATERIALS

# INTRODUCTION
## Imports

In [1]:
import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

from dcss.plotting import plot_knn_decision_boundaries
from dcss.plotting import custom_seaborn
custom_seaborn()

## A Very Brief Refresher on Linear and Logistic Regression Models:

## Preparing the Data

In [2]:
vdem_fh_df = pd.read_csv("../data/vdem_internet_freedom_combined/vdem_fh_combined.csv")
vdem_df = pd.read_csv("../data/vdem_internet_freedom_combined/vdem_only.csv")
vdem_df.head()

,country_name,year,e_regionpol,v2x_regime,v2x_polyarchy,v2x_libdem,v2x_partipdem,v2x_delibdem,v2x_egaldem,v2smgovdom_osp,v2smgovfilprc_osp,v2smgovsmcenprc_osp,v2smonper_osp,v2smarrest_osp
0,Mexico,2019,2,2.0,0.710,0.486,0.414,0.469,0.422,2.118,3.829,3.760,3.590,2.873
1,Suriname,2019,10,2.0,0.736,0.550,0.409,0.598,0.527,2.888,3.476,3.552,2.618,1.953
2,Sweden,2019,5,3.0,0.874,0.829,0.618,0.791,0.776,3.779,3.903,3.955,3.465,2.789
3,Switzerland,2019,5,3.0,0.873,0.827,0.776,0.831,0.803,3.792,3.885,3.926,3.304,2.795
4,Ghana,2019,4,3.0,0.718,0.608,0.338,0.619,0.529,3.580,3.446,3.713,3.288,2.301

## The Train-Test Split

In [3]:
from sklearn.model_selection import train_test_split

X = vdem_fh_df[['v2x_polyarchy', 'v2x_libdem', 'v2x_partipdem', 'v2x_delibdem', 'v2x_egaldem',]]
y = vdem_fh_df[['Total Score']]

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, random_state=23)

# Supervised Learning with Linear Regression

## Ordinary Least Squares (OLS) Regression

In [4]:
from sklearn.linear_model import LinearRegression
ols = LinearRegression()

In [5]:
ols.fit(X_train, y_train)

LinearRegression()

In [6]:
print("Intercept", list(X_train.columns))
print(ols.intercept_, ols.coef_)

Intercept ['v2x_polyarchy', 'v2x_libdem', 'v2x_partipdem', 'v2x_delibdem', 'v2x_egaldem']
[20.63811519] [[ 50.39585893  39.56204743  -8.08759862  13.15629676 -23.17231143]]

In [7]:
ols.score(X_train, y_train)

0.8001472299432686

## CROSS-VALIDATION

### Putting The Two Together: OLS and CV

In [8]:
from sklearn.model_selection import cross_val_score

cross_val_score(ols, X_train, y_train, cv=5)

array([0.83058131, 0.78927647, 0.49840463, 0.79752537, 0.43638926])

In [9]:
from sklearn.model_selection import ShuffleSplit

shuffsplit = ShuffleSplit(n_splits=5, test_size=0.2, random_state=42)

olscv_score = cross_val_score(ols, X_train, y_train, cv=shuffsplit)
olscv_score

array([0.69717758, 0.75979355, 0.85291181, 0.75438354, 0.82520158])

### Cheating on the Test

In [10]:
olscv_score.mean()

np.float64(0.7778936127600506)

In [11]:
ols.score(X_test, y_test)

0.7138660952137657

## Regularization via Ridge Regression

In [12]:
from sklearn.linear_model import Ridge

X = vdem_fh_df[['v2x_polyarchy', 'v2x_libdem', 'v2x_partipdem', 'v2x_delibdem', 'v2x_egaldem',]]
y = vdem_fh_df[['Total Score']]

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, random_state=2)
shuffsplit = ShuffleSplit(n_splits=15, test_size=0.2, random_state=2)

ridgereg = Ridge(1)
ridgecv_score = cross_val_score(ridgereg, X_train, y_train, cv=shuffsplit)
print(ridgecv_score)
print(f"Mean: {ridgecv_score.mean()}")

[0.76925883 0.6824065  0.55949992 0.8241338  0.68662485 0.70895771
 0.75976052 0.81467692 0.45224363 0.70896388 0.8031883  0.79628239
 0.80544664 0.59523827 0.75607114]
Mean: 0.714850220864512

## Regularization via Lasso Regression

In [13]:
from sklearn.linear_model import Lasso

lassoreg = Lasso(1)
lassocv_score = cross_val_score(lassoreg, X_train, y_train, cv=shuffsplit)
print(lassocv_score)
print(f"Mean: {lassocv_score.mean()}")

[0.66584977 0.57869829 0.56643005 0.80293505 0.63309778 0.67545323
 0.68783192 0.76130175 0.40440872 0.6672346  0.70078081 0.75350907
 0.78697977 0.56112952 0.7518551 ]
Mean: 0.6664996955827664

In [14]:
alphas = np.linspace(0.01, 2, 50)

ridge_r2s = []
lasso_r2s = []

olscv_score = cross_val_score(LinearRegression(), X_train, y_train, cv=shuffsplit)

for alpha in alphas:
    new_ridge = Ridge(alpha)
    ridge_r2s.append(cross_val_score(new_ridge, X_train, y_train, cv=shuffsplit).mean())
    
    new_lasso = Lasso(alpha)
    new_lasso.fit(X_train, y_train)
    lasso_r2s.append(cross_val_score(new_lasso, X_train, y_train, cv=shuffsplit).mean())
    
r2s = pd.DataFrame(
    zip(alphas, ridge_r2s, lasso_r2s), 
    columns = ["alpha", "Ridge Regression", "Lasso Regression"])

In [15]:
fig, ax = plt.subplots()
sns.lineplot(x="alpha", y="Ridge Regression", data = r2s, label="Ridge", linestyle='solid')
sns.lineplot(x="alpha", y="Lasso Regression", data = r2s, label = "Lasso", linestyle='dashed')
ax.axhline(olscv_score.mean(), label="OLS", linestyle='dotted', color="darkgray")
ax.set(xlabel='alpha values for Ridge and Lasso Regressions', ylabel='R2')
sns.despine()
ax.legend()
plt.show()

/var/folders/b5/h41fdq7j1ys3hmsdxf5sk9jh0000gp/T/ipykernel_45447/2372481932.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [16]:
best_alpha = alphas[ridge_r2s.index(max(ridge_r2s))]
best_alpha

np.float64(0.2942857142857143)

In [17]:
best_ridgereg = Ridge(best_alpha)
best_ridgereg.fit(X_train, y_train)

pd.DataFrame(
    [
        *best_ridgereg.intercept_, 
        *np.ravel(best_ridgereg.coef_)], 
    index=['Intercept', *X_test.columns]
)

                       0
Intercept      22.769359
v2x_polyarchy  21.976134
v2x_libdem     20.601121
v2x_partipdem  22.536885
v2x_delibdem    5.303777
v2x_egaldem     7.585864

In [18]:
best_ridgereg.score(X_test, y_test)

0.7472740093285362

## Model Interpretation

In [19]:
predictions = np.round(best_ridgereg.predict(X_test))

In [20]:
np.ravel(predictions)

array([41., 40., 37., 34., 52., 82., 49., 33., 63., 49., 50., 73., 77.,
       51., 29., 34., 33.])

In [21]:
preds = pd.DataFrame({"Total Score": y_test['Total Score'], "Predicted Score": np.ravel(predictions), "Country":  vdem_fh_df.loc[y_test.index]['Country']})
preds

    Total Score  Predicted Score     Country
0            64             41.0      Angola
28           47             40.0      Jordan
62           24             37.0     Vietnam
29           32             34.0  Kazakhstan
23           55             52.0       India
10           87             82.0      Canada
30           68             49.0       Kenya
51           35             33.0    Thailand
36           60             63.0      Mexico
32           52             49.0     Lebanon
56           56             50.0     Ukraine
1            72             73.0   Argentina
27           73             77.0       Japan
35           57             51.0    Malaysia
50           17             29.0       Syria
9            43             34.0    Cambodia
60           26             33.0  Uzbekistan

# CLASSIFICATION WITH LOGISTIC REGRESSION

In [22]:
y = np.where(vdem_df["v2x_regime"] <= 1, 0, 1).copy()

X = vdem_df[[
                 'v2smgovdom_osp', 
                 "v2smgovfilprc_osp", 
                 "v2smgovsmcenprc_osp", 
                 "v2smonper_osp", 
                 "v2smarrest_osp", 
]]

In [23]:
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=23)
shuffsplit = ShuffleSplit(n_splits=5, test_size=0.2, random_state=42)

log_reg = cross_val_score(
    LogisticRegression(), 
    X_train, 
    y_train, 
    cv=shuffsplit)
print(log_reg)
print(f"Mean: {log_reg.mean()}")

[0.96296296 0.85185185 0.88888889 0.85185185 0.7037037 ]
Mean: 0.8518518518518519

In [24]:

log_reg_regularized = cross_val_score(
    LogisticRegression(C=0.5), 
    X_train, 
    y_train, 
    cv=shuffsplit)
print(log_reg_regularized)
print(f"Mean: {log_reg_regularized.mean()}")

[0.96296296 0.85185185 0.88888889 0.85185185 0.7037037 ]
Mean: 0.8518518518518519

# CONCLUSION
## Key Points